version: '3'

# See environment-specific taskfiles for commands about
# that environment.
includes:
  be:
    taskfile: ./Taskfile.backend.yml
    dir: backend
  fe:
    taskfile: ./Taskfile.frontend.yml
    dir: frontend
