[project]
name = "rotini-backend"
version = "0.0.0"
dependencies = [
    "fastapi~=0.101",
    "uvicorn[standard]",
    "python-multipart",
    "psycopg2",
    "typing_extensions",
    "pydantic~=2.0",
    "pyjwt~=2.8",
    "argon2-cffi~=23.1"
]

[project.optional-dependencies]
dev = [
    "anyio~=3.7.0",
    "black~=23.7.0",
    "pylint~=2.17.0",
    "pytest",
    "httpx"
] 

[tool.setuptools]
packages = ["rotini"]

[tool.pytest.ini_options]
pythonpath=[
    ".",
    "./rotini",
]

