#!/bin/bash

PYTHON=.venv/bin/python

$PYTHON -m piptools compile -o requirements.txt pyproject.toml --no-header \
    && $PYTHON -m piptools compile -o requirements_dev.txt --no-header --extra dev --constraint requirements.txt pyproject.toml 
