name: Backend Pipeline

on:
  workflow_call:
    inputs:
      task-version:
        required: true
        type: string
    outputs:
      pipeline-success:
        value: ${{ jobs.notify-success.outputs.pipeline_success }}

env:
  ROTINI_CI: 1

defaults:
  run:
    working-directory: backend

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup-backend-environment
        with:
          task-version: ${{ inputs.task-version }}
  lint:
    runs-on: ubuntu-latest
    name: Lint
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup-backend-environment
        with:
          task-version: ${{ inputs.task-version }}
      - name: Lint
        run: |
          task be:lint
  test:
    runs-on: ubuntu-latest
    name: Test
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup-backend-environment
        with:
          task-version: ${{ inputs.task-version }}
      - name: Test
        run: |
          task be:test
  notify-success:
    runs-on: ubuntu-latest
    name: Notify success
    needs: [lint, test]
    steps:
      - id: set-output
        working-directory: /
        run: echo "pipeline_success=true" >> "$GITHUB_OUTPUT"
    outputs:
      pipeline_success: ${{ steps.set-output.outputs.pipeline_success }}
